### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by zthxxx** [zthxxx/zsh-history-enquirer#44]
- [ ] refactor and remove enquirer
- [ ] rename project name and bin file name
- [ ] documents for features how to use
- [ ] support multiline input
